import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.rainydayparents.com/login');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('admin.devrainyday@yopmail.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('6');
  await page.getByRole('textbox').nth(1).fill('0');
  await page.getByRole('textbox').nth(2).fill('9');
  await page.getByRole('textbox').nth(3).fill('0');
  await page.getByRole('textbox').nth(4).fill('7');
  await page.getByRole('textbox').nth(5).fill('0');
  await page.getByRole('link', { name: 'Activities' }).click();
  await page.getByRole('button', { name: 'Create Activity' }).click();
  await page.getByRole('textbox', { name: 'Activity Name*' }).click();
  await page.getByRole('textbox', { name: 'Activity Name*' }).fill('Regional kid play');
  await page.getByRole('textbox', { name: 'Activity Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'What To Expect*' }).fill('this is a test activity');
  await page.getByRole('button', { name: 'Select event type' }).click();
  await page.locator('div').filter({ hasText: /^Library \/ Storytime$/ }).click();
  await page.getByRole('button', { name: 'Select age groups' }).click();
  await page.getByRole('checkbox', { name: 'Prenatal' }).check();
  await page.locator('div').filter({ hasText: 'Drop-inIndoorSuitable for' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Enter address or search...' }).click();
  await page.getByRole('textbox', { name: 'Enter address or search...' }).fill('mindbow');
  await page.getByText('Mindbowser Inc, Pan Card Club').click();
  await page.getByRole('textbox', { name: 'Yelp (optional)' }).click();
  await page.getByRole('textbox', { name: 'Yelp (optional)' }).fill('www.google.com');
  await page.getByRole('textbox', { name: 'Yelp (optional)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Website (optional)' }).fill('www.gb.com');
  await page.getByRole('textbox', { name: 'Website (optional)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Google Reviews Page (optional)' }).fill('www.fb.com');
  await page.getByRole('textbox', { name: 'Google Reviews Page (optional)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Pre-registration required' }).press('Tab');
  await page.getByRole('button', { name: 'Select Image' }).press('Tab');
  await page.locator('.absolute.right-1').press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('Tab');
  await page.getByRole('button', { name: 'Create Activity' }).press('Enter');
  await page.getByRole('textbox', { name: 'Google Reviews Page (optional)' }).click();
  await page.getByRole('textbox', { name: 'Google Reviews Page (optional)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Pre-registration required' }).press('Tab');
  await page.getByRole('button', { name: 'Select Image' }).press('Tab');
  await page.locator('.absolute.right-1').press('Tab');
  await page.getByRole('button', { name: 'Cancel' }).press('Tab');
  await page.getByRole('button', { name: 'Create Activity' }).press('Enter');
 
});